language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: 
  - phpunit